### ISSUE TITLE
Installation error for insomnia-plugin-github-apps-helper

### ISSUE THREAD

**Issue by martin389** [swinton/insomnia-plugin-github-apps-helper#22]
👋 I'm receiving the following error when I follow the installation steps:

```
Error: Yarn error warning insomnia-plugin-github-apps-helper > @octokit/app@2.2.5: '@octokit/app' will be repurposed in future. Use '@octokit/auth-app' instead

    at file:///Applications/Insomnia.app/Contents/Resources/app.asar/bundle.js:103518:16
    at ChildProcess.exithandler (child_process.js:295:7)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

I'm on version: Insomnia Core 2020.5.2.

**Comment by swinton** [comment]
Hi @martin389 thanks for letting me know. 

Were you able to install the plug-in despite the error, or did the installation fail?

I recognize this needs to be addressed, but trying to understand if this is blocking. 

Thank you 🙇

**Comment by martin389** [comment]
Thanks @swinton!

The installation is failing for me: `Failed to install insomnia-plugin-github-apps-helper`

**Comment by swinton** [comment]
PR is up in #24.

**Comment by swinton** [comment]
Seeing a new error now, unfortunately, in Insomnia:

> Error: Cannot find module '/Users/swinton/Library/Application Support/Insomnia/plugins/insomnia-plugin-github-apps-helper/node_modules/@octokit/request/index.js'. Please verify that the package.json has a valid "main" entry

Not totally sure of a fix, I _may_ need to vendor in the @octokit dependencies 🤔

**Comment by swinton** [comment]
@martin389 I'm [packaging this differently now](https://github.com/swinton/insomnia-plugin-github-apps-helper/pull/25) to workaround [the previous error](https://github.com/swinton/insomnia-plugin-github-apps-helper/issues/22#issuecomment-754949439).

I confirmed it's working for me again now, would you mind trying this again? Thank you! :bow:

**Comment by martin389** [comment]
Thank you so much @swinton 🚀  Its working for me now 👍
