### ISSUE TITLE
npm error when attempting to install plugin on Windows Client

### ISSUE THREAD

**Issue by IAmHughes** [swinton/insomnia-plugin-github-apps-helper#8]
When using the Windows 10 client for Insomnia, the plugin install fails. I followed the same steps as the `README` lays out and they worked on my Macbook, however my Windows Desktop wasn't as happy. I do have NPM installed (v6.4.1) on my Windows box.

![image](https://user-images.githubusercontent.com/2894107/55901407-e2cbc700-5b8e-11e9-85fe-b72064b968cd.png)

**Comment by swinton** [comment]
@IAmHughes 🤔 

Could you see if you get the same error when installing one of [the other plugins](https://github.com/getinsomnia/insomnia#plugins), perhaps [this one](https://www.npmjs.com/package/insomnia-plugin-customtimestamp)?

**Comment by IAmHughes** [comment]
@swinton hmmm, should've done that myself. I'm getting the same error (with the plugin name changing but the rest the same).

**Comment by swinton** [comment]
I believe this is related to https://github.com/getinsomnia/insomnia/issues/1202

Closing in favor of that issue.
